### ISSUE TITLE
Предложение по .gitignore

### ISSUE THREAD

**Issue by nagayev** [mathculthello/savva4#3]
Обычно на github не принято выкладывать файлы, не относящиеся к непосредственно коду проекта.
Я предлагаю исключить не md файлы из репозитория (т.е добавить в .gitignore).

**Comment by aeifn** [comment]
А куда деть картинки, пдфки и настройки?

**Comment by nagayev** [comment]
@aeifn Если настройки это файл config.yml, то можно оставить. Как и картинки.
А pdf можно закинуть на какой-нибудь яндекс диск наверное и скопировать с него ссылку на файл.

**Comment by nagayev** [comment]
Еще одно предложение: возможно стоит переименовать репозиторий.
Я так и не понял чем отличается savva4 от savva3.
Если что-то из этого старая версия сайта, то наверное стоит заархивировать репозиторий и переименовать в что-то вроде old-website.

**Comment by aeifn** [comment]
> @aeifn Если настройки это файл config.yml, то можно оставить. Как и картинки.
> А pdf можно закинуть на какой-нибудь яндекс диск наверное и скопировать с него ссылку на файл.

Не, на яндекс-диске все потеряется в конце концов. Удобно было бы использовать git-lfs, но github pages не совместимы с ним, увы.
