### ISSUE TITLE
Опечатка

### ISSUE THREAD

**Issue by Feelinglight** [mathculthello/savva4#4]
В конспекте "100 уроков математики" опечатка в упражнении 1.34 e) : 4-й член ряда неверный

Сейчас ----------> $1 + \frac{2}{3} + \frac{3}{5} + \frac{5}{9} + ... + \frac{n}{2n - 1} + ...$
Должно быть -> $1 + \frac{2}{3} + \frac{3}{5} + \frac{4}{7} + ... + \frac{n}{2n - 1} + ...$

**Comment by aeifn** [comment]
Пожалуйста, перенесите тикет в репозиторий автора https://github.com/nkrishelie/mathempire/issues.
